var Login = require("./User/Login");
var Register = require("./User/Register");
var ChangInfor = require("./User/ChangInfor");
var CheckLogin = require("./User/CheckLogin");
var NewRecyclables = require("./Recyclables/NewRecyclables");
var ChangeStatusRece = require("./Recyclables/ChangStatusRecy");
var getStatusReady = require("./Recyclables/GetStatusReady");
var CreateHistory = require("./Member/CreateHistory");
var GetHistory = require("./Member/GetHistory");
var GetGift = require("./Gift/GetGift");
var GetLevel = require("./Recyclables/GetLevel");
var GetSocre = require("./Member/GetScore");
var CreateNotify = require("./Notify/CreateNotity");
var GetNotify = require("./Notify/GetNotify");
var GetHistoryScore = require("./Member/getHistoryScrore");
var GetHistoryRecyclables = require("./Recyclables/GetHistoryRecyclables");
var GetInfor = require("./User/GetInfor");
module.exports = function (app) {
  console.log("this is to to Controllers");
  Login(app);
  Register(app);
  ChangInfor(app);
  CheckLogin(app);
  NewRecyclables(app);
  ChangeStatusRece(app);
  getStatusReady(app);
  CreateHistory(app);
  GetHistory(app);
  GetGift(app);
  GetLevel(app);
  GetSocre(app);
  CreateNotify(app);
  GetNotify(app);
  GetHistoryScore(app);
  GetHistoryRecyclables(app);
  GetInfor(app);
};
